// ARCHIVED: SSHSession key parsing methods
// Removed: Feb 2026, Session 21 (Phase 1a)
// Reason: Duplicate of SSHKeyParser.swift — SSHSession contained ~286 lines of key
//         parsing that was a near-copy of the standalone SSHKeyParser, but with a
//         real ECDSA bug (didn't strip mpint padding for ECDSA keys in OpenSSH format,
//         causing ~50% of ECDSA-in-OpenSSH keys to fail). SSHKeyParser is the correct
//         version. buildAuthMethod now delegates to SSHKeyParser.parsePrivateKey().
//
// Original location: Sources/SSH/SSHSession.swift, lines 293-581
// Original imports removed: `import Crypto`, `@_spi(CryptoExtras) import _CryptoExtras`

    // MARK: - Key Parsing
    
    /// Parse a private key from PEM data
    private func parsePrivateKey(_ data: Data, passphrase: String?) throws -> NIOSSHPrivateKey {
        logger.debug("[KeyParse] parsePrivateKey called with \(data.count) bytes")
        
        guard let pemString = String(data: data, encoding: .utf8) else {
            throw SSHSessionError.invalidKey("[v2] Unable to read key as UTF-8")
        }
        
        logger.debug("[KeyParse] PEM header check: contains OPENSSH=\(pemString.contains("OPENSSH PRIVATE KEY"))")
        
        // Encrypted keys require passphrase handling
        if pemString.contains("ENCRYPTED") && passphrase == nil {
            throw SSHSessionError.invalidKey("[v2] Key is encrypted but no passphrase provided")
        }
        
        // Try OpenSSH format first (most common modern format from ssh-keygen)
        if pemString.contains("OPENSSH PRIVATE KEY") {
            logger.debug("[KeyParse] Detected OpenSSH format, calling parseOpenSSHPrivateKey")
            return try parseOpenSSHPrivateKey(pemString, passphrase: passphrase)
        }
        
        // Try RSA (common for cloud providers)
        if pemString.contains("RSA PRIVATE KEY") || pemString.contains("BEGIN PRIVATE KEY") {
            do {
                // Use swift-crypto's _RSA for PEM parsing
                let rsaKey = try _RSA.Signing.PrivateKey(pemRepresentation: pemString)
                return NIOSSHPrivateKey(rsaKey: rsaKey)
            } catch {
                logger.warning("RSA key parsing failed: \(error.localizedDescription)")
                throw SSHSessionError.invalidKey("Failed to parse RSA key: \(error.localizedDescription)")
            }
        }
        
        // Try ECDSA
        if pemString.contains("EC PRIVATE KEY") {
            // Try P-256 first (most common)
            if let p256Key = try? P256.Signing.PrivateKey(pemRepresentation: pemString) {
                return NIOSSHPrivateKey(p256Key: p256Key)
            }
            // Try P-384
            if let p384Key = try? P384.Signing.PrivateKey(pemRepresentation: pemString) {
                return NIOSSHPrivateKey(p384Key: p384Key)
            }
            // Try P-521
            if let p521Key = try? P521.Signing.PrivateKey(pemRepresentation: pemString) {
                return NIOSSHPrivateKey(p521Key: p521Key)
            }
            throw SSHSessionError.invalidKey("ECDSA key curve not supported")
        }
        
        throw SSHSessionError.invalidKey("[v2] Unsupported key format. Supported: RSA, ECDSA, Ed25519")
    }
    
    /// Parse OpenSSH private key format (BEGIN OPENSSH PRIVATE KEY)
    /// This is the default format generated by ssh-keygen since OpenSSH 6.5


    private func parseOpenSSHPrivateKey(_ pemString: String, passphrase: String?) throws -> NIOSSHPrivateKey {
        logger.debug("[KeyParse] parseOpenSSHPrivateKey: Starting")
        
        // Extract base64 content between PEM headers
        let lines = pemString.components(separatedBy: .newlines)
        var base64Content = ""
        var inKey = false
        
        for line in lines {
            if line.contains("BEGIN OPENSSH PRIVATE KEY") {
                inKey = true
                continue
            }
            if line.contains("END OPENSSH PRIVATE KEY") {
                break
            }
            if inKey {
                base64Content += line.trimmingCharacters(in: .whitespaces)
            }
        }
        
        logger.debug("[KeyParse] Base64 content length: \(base64Content.count)")
        
        guard let keyData = Data(base64Encoded: base64Content) else {
            throw SSHSessionError.invalidKey("Invalid base64 in OpenSSH key")
        }
        
        logger.debug("[KeyParse] Decoded key data: \(keyData.count) bytes")
        
        // Parse OpenSSH key format
        // See: https://github.com/openssh/openssh-portable/blob/master/PROTOCOL.key
        var offset = 0
        
        // Magic: "openssh-key-v1\0"
        let magic = "openssh-key-v1\0"
        let magicBytes = Array(magic.utf8)
        guard keyData.count > magicBytes.count else {
            throw SSHSessionError.invalidKey("Key too short")
        }
        
        let actualMagic = Array(keyData.prefix(magicBytes.count))
        guard actualMagic == magicBytes else {
            throw SSHSessionError.invalidKey("Invalid OpenSSH key magic")
        }
        offset = magicBytes.count
        logger.debug("[KeyParse] Magic verified, offset now: \(offset)")
        
        // Helper to read a uint32
        func readUInt32() throws -> UInt32 {
            guard offset + 4 <= keyData.count else {
                throw SSHSessionError.invalidKey("Unexpected end of key data at offset \(offset)")
            }
            let value = keyData.withUnsafeBytes { ptr in
                ptr.loadUnaligned(fromByteOffset: offset, as: UInt32.self).bigEndian
            }
            offset += 4
            return value
        }
        
        // Helper to read a string (length-prefixed)
        func readString() throws -> Data {
            let length = try Int(readUInt32())
            logger.debug("[KeyParse] readString: length=\(length) at offset \(offset - 4)")
            guard length >= 0 && offset + length <= keyData.count else {
                throw SSHSessionError.invalidKey("Invalid string length \(length) at offset \(offset)")
            }
            let data = keyData[offset..<(offset + length)]
            offset += length
            return Data(data)
        }
        
        // Cipher name
        let cipherData = try readString()
        let cipherName = String(data: cipherData, encoding: .utf8) ?? ""
        logger.debug("[KeyParse] Cipher: '\(cipherName)'")
        
        // KDF name
        let kdfData = try readString()
        let kdfName = String(data: kdfData, encoding: .utf8) ?? ""
        logger.debug("[KeyParse] KDF: '\(kdfName)'")
        
        // KDF options
        let kdfOptions = try readString()
        logger.debug("[KeyParse] KDF options: \(kdfOptions.count) bytes")
        
        // Number of keys (usually 1)
        let numKeys = try readUInt32()
        logger.debug("[KeyParse] Number of keys: \(numKeys)")
        guard numKeys == 1 else {
            throw SSHSessionError.invalidKey("Multiple keys in file not supported")
        }
        
        // Public key (we skip this, will extract from private section)
        let publicKeyBlob = try readString()
        logger.debug("[KeyParse] Public key blob: \(publicKeyBlob.count) bytes")
        
        // Private key section (may be encrypted)
        // IMPORTANT: Create a new Data to reset indices to 0
        let privateData = Data(try readString())
        logger.debug("[KeyParse] Private data: \(privateData.count) bytes")
        
        // Check if encrypted
        if cipherName != "none" {
            guard passphrase != nil else {
                throw SSHSessionError.invalidKey("Key is encrypted but no passphrase provided")
            }
            // TODO: Implement decryption for aes256-ctr, aes256-cbc, etc.
            throw SSHSessionError.invalidKey("Encrypted OpenSSH keys not yet supported. Use: ssh-keygen -p -m PEM -f <keyfile> to convert")
        }
        
        // Parse unencrypted private key section
        var privOffset = 0
        
        func readPrivUInt32() throws -> UInt32 {
            guard privOffset + 4 <= privateData.count else {
                throw SSHSessionError.invalidKey("Unexpected end of private key data")
            }
            let value = privateData.withUnsafeBytes { ptr in
                ptr.loadUnaligned(fromByteOffset: privOffset, as: UInt32.self).bigEndian
            }
            privOffset += 4
            return value
        }
        
        func readPrivString() throws -> Data {
            let length = try Int(readPrivUInt32())
            guard privOffset + length <= privateData.count else {
                throw SSHSessionError.invalidKey("Unexpected end of private key data")
            }
            let data = Data(privateData[privOffset..<(privOffset + length)])
            privOffset += length
            return data
        }
        
        // Check bytes (should be identical - used for passphrase verification)
        let check1 = try readPrivUInt32()
        let check2 = try readPrivUInt32()
        guard check1 == check2 else {
            throw SSHSessionError.invalidKey("Key decryption failed (check bytes mismatch)")
        }
        
        // Key type
        let keyTypeData = try readPrivString()
        guard let keyType = String(data: keyTypeData, encoding: .utf8) else {
            throw SSHSessionError.invalidKey("Invalid key type encoding")
        }
        
        logger.debug("[KeyParse] Parsed key type: '\(keyType)'")
        
        switch keyType {
        case "ssh-ed25519":
            // Ed25519: public key (32 bytes) + private key (64 bytes = seed + public)
            let publicKey = try readPrivString()  // 32 bytes
            let privateKey = try readPrivString() // 64 bytes
            
            guard publicKey.count == 32, privateKey.count == 64 else {
                throw SSHSessionError.invalidKey("Invalid Ed25519 key length")
            }
            
            // The first 32 bytes of the private key is the seed
            let seed = privateKey.prefix(32)
            let ed25519Key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed)
            return NIOSSHPrivateKey(ed25519Key: ed25519Key)
            
        case "ecdsa-sha2-nistp256":
            // ECDSA P-256
            // BUG: Missing mpint padding strip — ~50% of ECDSA keys would fail
            _ = try readPrivString() // curve identifier "nistp256"
            let publicPoint = try readPrivString() // uncompressed point
            let privateScalar = try readPrivString() // private scalar
            
            let p256Key = try P256.Signing.PrivateKey(rawRepresentation: privateScalar)
            return NIOSSHPrivateKey(p256Key: p256Key)
            
        case "ecdsa-sha2-nistp384":
            // ECDSA P-384
            // BUG: Missing mpint padding strip
            _ = try readPrivString()
            _ = try readPrivString()
            let privateScalar = try readPrivString()
            
            let p384Key = try P384.Signing.PrivateKey(rawRepresentation: privateScalar)
            return NIOSSHPrivateKey(p384Key: p384Key)
            
        case "ecdsa-sha2-nistp521":
            // ECDSA P-521
            // BUG: Missing mpint padding strip
            _ = try readPrivString()
            _ = try readPrivString()
            let privateScalar = try readPrivString()
            
            let p521Key = try P521.Signing.PrivateKey(rawRepresentation: privateScalar)
            return NIOSSHPrivateKey(p521Key: p521Key)
            
        case "ssh-rsa":
            // RSA key in OpenSSH format
            func stripMpintPadding(_ data: Data) -> Data {
                if let first = data.first, first == 0x00, data.count > 1 {
                    return Data(data.dropFirst())
                }
                return data
            }
            
            let nRaw = try readPrivString() // modulus
            let eRaw = try readPrivString() // public exponent  
            let dRaw = try readPrivString() // private exponent
            _ = try readPrivString() // iqmp (inverse of q mod p) - not needed for swift-crypto
            let pRaw = try readPrivString() // prime 1
            let qRaw = try readPrivString() // prime 2
            
            let n = stripMpintPadding(nRaw)
            let e = stripMpintPadding(eRaw)
            let d = stripMpintPadding(dRaw)
            let p = stripMpintPadding(pRaw)
            let q = stripMpintPadding(qRaw)
            
            logger.debug("RSA key components (after mpint strip): n=\(n.count) bytes, e=\(e.count) bytes, d=\(d.count) bytes, p=\(p.count) bytes, q=\(q.count) bytes")
            
            let rsaKey = try _RSA.Signing.PrivateKey(n: n, e: e, d: d, p: p, q: q)
            return NIOSSHPrivateKey(rsaKey: rsaKey)
            
        default:
            throw SSHSessionError.invalidKey("Unsupported key type: \(keyType)")
        }
    }
