#!/bin/bash
# add_file_provider_target.sh
# Run this to add the File Provider extension target to the Xcode project
# Or manually: File > New > Target > iOS File Provider Extension

echo "📂 File Provider Extension Setup Guide"
echo "========================================"
echo ""
echo "This extension enables SFTP access through Files.app."
echo "Each saved SSH connection will appear in the Files.app sidebar."
echo ""
echo "STEP 1: Open Xcode"
echo "=================="
echo "   open /Users/daiimus/Projects/Repositories/geistty/Geistty/Geistty.xcodeproj"
echo ""
echo "STEP 2: Add App Group (Main App)"
echo "================================="
echo "   1. Select 'Geistty' target in project navigator"
echo "   2. Go to 'Signing & Capabilities' tab"
echo "   3. Click '+ Capability'"
echo "   4. Add 'App Groups'"
echo "   5. Add group: group.com.geistty.fileprovider"
echo ""
echo "STEP 3: Add File Provider Extension Target"
echo "==========================================="
echo "   1. File → New → Target..."
echo "   2. Choose 'File Provider Extension' under iOS Application Extension"
echo "   3. Product Name: GeisttyFileProvider"
echo "   4. Bundle Identifier: com.geistty.app.fileprovider"
echo "   5. Click Finish"
echo "   6. Xcode will ask to activate scheme - click 'Activate'"
echo ""
echo "STEP 4: Replace Auto-generated Files"
echo "======================================"
echo "   1. Delete the auto-generated FileProvider.swift file"
echo "   2. In Project Navigator, right-click on GeisttyFileProvider group"
echo "   3. 'Add Files to Geistty...'"
echo "   4. Navigate to GeisttyFileProvider/ folder"
echo "   5. Select all .swift files:"
echo "      - FileProviderExtension.swift"
echo "      - FileProviderItem.swift"
echo "      - FileProviderEnumerator.swift"
echo "   6. Ensure 'GeisttyFileProvider' target is checked"
echo "   7. Click 'Add'"
echo ""
echo "STEP 5: Add Shared Source Files to Extension Target"
echo "===================================================="
echo "   These files need to be compiled in BOTH the main app and extension:"
echo ""
echo "   1. In Project Navigator, select each file and check 'Target Membership'"
echo "      in the File Inspector (right panel) for 'GeisttyFileProvider':"
echo ""
echo "      Sources/SFTP/"
echo "      - SFTPChannel.swift"
echo "      - SFTPClient.swift"
echo ""
echo "      Sources/SSH/"
echo "      - NIOSSHConnection.swift (for SSH connection)"
echo ""
echo "      Sources/Auth/"
echo "      - KeychainManager.swift (for shared keychain)"
echo "      - CredentialProvider.swift"
echo ""
echo "STEP 6: Configure Extension Entitlements"
echo "========================================="
echo "   1. Select GeisttyFileProvider target"
echo "   2. Go to 'Signing & Capabilities'"
echo "   3. Add 'App Groups' capability"
echo "   4. Add same group: group.com.geistty.fileprovider"
echo ""
echo "STEP 7: Update Info.plist"
echo "=========================="
echo "   Replace the auto-generated Info.plist with our custom one:"
echo "   - Copy GeisttyFileProvider/Info.plist contents"
echo "   - Or delete auto-generated and add our Info.plist to target"
echo ""
echo "STEP 8: Build & Test"
echo "===================="
echo "   1. Select 'Geistty' scheme (not GeisttyFileProvider)"
echo "   2. Build for device: Cmd+B"
echo "   3. Run on device"
echo "   4. Open Files.app"
echo "   5. Look for 'Geistty' in Locations sidebar after connecting to a server"
echo ""
echo "ARCHITECTURE NOTES"
echo "==================="
echo "   - One domain per saved SSH connection"
echo "   - Domain format: sftp-<host>-<port>-<username>"
echo "   - Main app registers domains via NSFileProviderManager"
echo "   - Extension runs in separate process, shares credentials via App Group keychain"
echo "   - Files.app shows each server as a location in sidebar"
echo ""
echo "TROUBLESHOOTING"
echo "================"
echo "   - 'No such module NIOCore': Add NIO dependencies to extension target"
echo "   - Extension not appearing: Check domain registration in main app"
echo "   - Auth failures: Verify App Group keychain setup"
echo "   - Use Console.app with filter 'com.geistty.fileprovider' for extension logs"
echo ""
