//
//  SSHKeyParser.swift
//  Geistty
//
//  SSH private key parsing utilities
//  Extracted from SSHSession for sharing with File Provider extension
//

import Foundation
import NIOSSH
import Crypto
import _CryptoExtras
import os.log

private let logger = Logger(subsystem: "com.geistty", category: "SSHKeyParser")

/// SSH key parsing errors
public enum SSHKeyParseError: LocalizedError {
    case invalidKey(String)
    case encryptedKeyNoPassphrase
    case unsupportedFormat(String)
    
    public var errorDescription: String? {
        switch self {
        case .invalidKey(let msg): return "Invalid SSH key: \(msg)"
        case .encryptedKeyNoPassphrase: return "Key is encrypted but no passphrase provided"
        case .unsupportedFormat(let format): return "Unsupported key format: \(format)"
        }
    }
}

/// Utility for parsing SSH private keys
public enum SSHKeyParser {
    
    /// Parse a private key from PEM data
    public static func parsePrivateKey(_ data: Data, passphrase: String? = nil) throws -> NIOSSHPrivateKey {
        logger.debug("🔑 parsePrivateKey called with \(data.count) bytes")
        
        guard let pemString = String(data: data, encoding: .utf8) else {
            throw SSHKeyParseError.invalidKey("Unable to read key as UTF-8")
        }
        
        // Encrypted keys require passphrase handling
        if pemString.contains("ENCRYPTED") && passphrase == nil {
            throw SSHKeyParseError.encryptedKeyNoPassphrase
        }
        
        // Try OpenSSH format first (most common modern format from ssh-keygen)
        if pemString.contains("OPENSSH PRIVATE KEY") {
            logger.debug("🔑 Detected OpenSSH format")
            return try parseOpenSSHPrivateKey(pemString, passphrase: passphrase)
        }
        
        // Try RSA (common for cloud providers)
        if pemString.contains("RSA PRIVATE KEY") || pemString.contains("BEGIN PRIVATE KEY") {
            do {
                let rsaKey = try _RSA.Signing.PrivateKey(pemRepresentation: pemString)
                logger.debug("🔑 Parsed RSA key")
                return NIOSSHPrivateKey(rsaKey: rsaKey)
            } catch {
                logger.warning("RSA key parsing failed: \(error.localizedDescription)")
                throw SSHKeyParseError.invalidKey("Failed to parse RSA key: \(error.localizedDescription)")
            }
        }
        
        // Try ECDSA
        if pemString.contains("EC PRIVATE KEY") {
            // Try P-256 first (most common)
            if let p256Key = try? P256.Signing.PrivateKey(pemRepresentation: pemString) {
                logger.debug("🔑 Parsed P-256 ECDSA key")
                return NIOSSHPrivateKey(p256Key: p256Key)
            }
            // Try P-384
            if let p384Key = try? P384.Signing.PrivateKey(pemRepresentation: pemString) {
                logger.debug("🔑 Parsed P-384 ECDSA key")
                return NIOSSHPrivateKey(p384Key: p384Key)
            }
            // Try P-521
            if let p521Key = try? P521.Signing.PrivateKey(pemRepresentation: pemString) {
                logger.debug("🔑 Parsed P-521 ECDSA key")
                return NIOSSHPrivateKey(p521Key: p521Key)
            }
            throw SSHKeyParseError.unsupportedFormat("ECDSA key curve not supported")
        }
        
        throw SSHKeyParseError.unsupportedFormat("Supported formats: RSA, ECDSA, Ed25519 (OpenSSH)")
    }
    
    /// Strip leading zero byte from SSH mpint format
    /// SSH mpint format adds a 0x00 prefix when the high bit is set to indicate positive number.
    /// swift-crypto expects raw unsigned integers without this padding.
    private static func stripMPIntPadding(_ data: Data) -> Data {
        guard data.count > 1, data[0] == 0 else { return data }
        return Data(data.dropFirst())
    }
    
    /// Parse OpenSSH private key format (-----BEGIN OPENSSH PRIVATE KEY-----)
    /// This is the default format generated by ssh-keygen since OpenSSH 6.5
    private static func parseOpenSSHPrivateKey(_ pemString: String, passphrase: String?) throws -> NIOSSHPrivateKey {
        logger.debug("🔑 parseOpenSSHPrivateKey: Starting")
        
        // Extract base64 content between PEM headers
        let lines = pemString.components(separatedBy: .newlines)
        var base64Content = ""
        var inKey = false
        
        for line in lines {
            if line.contains("BEGIN OPENSSH PRIVATE KEY") {
                inKey = true
                continue
            }
            if line.contains("END OPENSSH PRIVATE KEY") {
                break
            }
            if inKey {
                base64Content += line
            }
        }
        
        guard let keyData = Data(base64Encoded: base64Content) else {
            throw SSHKeyParseError.invalidKey("Failed to decode base64 key data")
        }
        
        logger.debug("🔑 Decoded \(keyData.count) bytes from base64")
        
        // OpenSSH key format:
        // "openssh-key-v1\0" (AUTH_MAGIC)
        // ciphername (string)
        // kdfname (string)
        // kdfoptions (string)
        // number of keys (uint32)
        // public key (string)
        // encrypted private key (string)
        
        let authMagic = "openssh-key-v1\0"
        guard keyData.starts(with: authMagic.data(using: .utf8)!) else {
            throw SSHKeyParseError.invalidKey("Invalid OpenSSH key magic")
        }
        
        var offset = authMagic.count
        
        // Read ciphername
        let cipherName = try readString(from: keyData, at: &offset)
        logger.debug("🔑 Cipher: \(cipherName)")
        
        // Read kdfname
        let kdfName = try readString(from: keyData, at: &offset)
        logger.debug("🔑 KDF: \(kdfName)")
        
        // Read kdfoptions
        let _ = try readString(from: keyData, at: &offset) // kdfoptions
        
        // Read number of keys
        let numKeys = try readUInt32(from: keyData, at: &offset)
        guard numKeys == 1 else {
            throw SSHKeyParseError.invalidKey("Multiple keys not supported")
        }
        
        // Skip public key
        let _ = try readString(from: keyData, at: &offset)
        
        // Read encrypted private section
        var privateData = try readString(from: keyData, at: &offset).data(using: .utf8) ?? Data()
        
        // If the private section wasn't a string, read as binary
        if privateData.isEmpty {
            offset -= 4 // back up to re-read length
            let privLen = try readUInt32(from: keyData, at: &offset)
            guard offset + Int(privLen) <= keyData.count else {
                throw SSHKeyParseError.invalidKey("Private key data truncated")
            }
            privateData = keyData.subdata(in: offset..<(offset + Int(privLen)))
        }
        
        // Handle encrypted keys
        if cipherName != "none" {
            guard let passphrase = passphrase else {
                throw SSHKeyParseError.encryptedKeyNoPassphrase
            }
            // Decrypt the private section
            privateData = try decryptPrivateData(privateData, cipher: cipherName, kdf: kdfName, passphrase: passphrase)
        }
        
        // Parse unencrypted private key data
        return try parsePrivateKeyData(privateData)
    }
    
    /// Read a uint32 in big-endian format
    private static func readUInt32(from data: Data, at offset: inout Int) throws -> UInt32 {
        guard offset + 4 <= data.count else {
            throw SSHKeyParseError.invalidKey("Unexpected end of key data")
        }
        let value = UInt32(data[offset]) << 24 |
                    UInt32(data[offset + 1]) << 16 |
                    UInt32(data[offset + 2]) << 8 |
                    UInt32(data[offset + 3])
        offset += 4
        return value
    }
    
    /// Read a length-prefixed string
    private static func readString(from data: Data, at offset: inout Int) throws -> String {
        let length = Int(try readUInt32(from: data, at: &offset))
        guard offset + length <= data.count else {
            throw SSHKeyParseError.invalidKey("String exceeds key data bounds")
        }
        let stringData = data.subdata(in: offset..<(offset + length))
        offset += length
        return String(data: stringData, encoding: .utf8) ?? ""
    }
    
    /// Read length-prefixed binary data
    private static func readBytes(from data: Data, at offset: inout Int) throws -> Data {
        let length = Int(try readUInt32(from: data, at: &offset))
        guard offset + length <= data.count else {
            throw SSHKeyParseError.invalidKey("Data exceeds key bounds")
        }
        let result = data.subdata(in: offset..<(offset + length))
        offset += length
        return result
    }
    
    /// Decrypt private key data (basic AES-256-CTR support)
    private static func decryptPrivateData(_ data: Data, cipher: String, kdf: String, passphrase: String) throws -> Data {
        // For now, only support common cipher
        guard cipher == "aes256-ctr" else {
            throw SSHKeyParseError.unsupportedFormat("Cipher \(cipher) not supported")
        }
        
        // This would require proper KDF derivation and AES decryption
        // For encrypted keys, users should use ssh-keygen to remove passphrase
        // or we implement full bcrypt KDF + AES-CTR
        throw SSHKeyParseError.invalidKey("Encrypted keys not yet supported - please use ssh-keygen -p to remove passphrase")
    }
    
    /// Parse the unencrypted private key data section
    private static func parsePrivateKeyData(_ data: Data) throws -> NIOSSHPrivateKey {
        var offset = 0
        
        // Check padding
        let check1 = try readUInt32(from: data, at: &offset)
        let check2 = try readUInt32(from: data, at: &offset)
        guard check1 == check2 else {
            throw SSHKeyParseError.invalidKey("Check bytes mismatch - wrong passphrase?")
        }
        
        // Read key type
        let keyType = try readString(from: data, at: &offset)
        logger.debug("🔑 Key type: \(keyType)")
        
        switch keyType {
        case "ssh-ed25519":
            // Ed25519: public key (32 bytes) + private key (64 bytes, first 32 are seed)
            let pubKey = try readBytes(from: data, at: &offset)
            let privKey = try readBytes(from: data, at: &offset)
            
            guard pubKey.count == 32 else {
                throw SSHKeyParseError.invalidKey("Invalid Ed25519 public key length: \(pubKey.count)")
            }
            guard privKey.count == 64 else {
                throw SSHKeyParseError.invalidKey("Invalid Ed25519 private key length: \(privKey.count)")
            }
            
            // Ed25519 private key in OpenSSH format is seed (32) + public (32)
            // We need just the seed
            let seed = privKey.prefix(32)
            let ed25519Key = try Curve25519.Signing.PrivateKey(rawRepresentation: seed)
            logger.info("🔑 Parsed Ed25519 key")
            return NIOSSHPrivateKey(ed25519Key: ed25519Key)
            
        case "ecdsa-sha2-nistp256":
            let _ = try readString(from: data, at: &offset) // curve name
            let pubKey = try readBytes(from: data, at: &offset)
            let privKey = try readBytes(from: data, at: &offset)
            
            let strippedPriv = stripMPIntPadding(privKey)
            let p256Key = try P256.Signing.PrivateKey(rawRepresentation: strippedPriv)
            logger.info("🔑 Parsed P-256 ECDSA key, pub=\(pubKey.count) priv=\(privKey.count)")
            return NIOSSHPrivateKey(p256Key: p256Key)
            
        case "ecdsa-sha2-nistp384":
            let _ = try readString(from: data, at: &offset)
            let pubKey = try readBytes(from: data, at: &offset)
            let privKey = try readBytes(from: data, at: &offset)
            
            let strippedPriv = stripMPIntPadding(privKey)
            let p384Key = try P384.Signing.PrivateKey(rawRepresentation: strippedPriv)
            logger.info("🔑 Parsed P-384 ECDSA key, pub=\(pubKey.count) priv=\(privKey.count)")
            return NIOSSHPrivateKey(p384Key: p384Key)
            
        case "ecdsa-sha2-nistp521":
            let _ = try readString(from: data, at: &offset)
            let pubKey = try readBytes(from: data, at: &offset)
            let privKey = try readBytes(from: data, at: &offset)
            
            let strippedPriv = stripMPIntPadding(privKey)
            let p521Key = try P521.Signing.PrivateKey(rawRepresentation: strippedPriv)
            logger.info("🔑 Parsed P-521 ECDSA key, pub=\(pubKey.count) priv=\(privKey.count)")
            return NIOSSHPrivateKey(p521Key: p521Key)
            
        case "ssh-rsa":
            // RSA: n, e, d, iqmp, p, q
            let n = try readBytes(from: data, at: &offset)
            let e = try readBytes(from: data, at: &offset)
            let d = try readBytes(from: data, at: &offset)
            let _ = try readBytes(from: data, at: &offset) // iqmp
            let p = try readBytes(from: data, at: &offset)
            let q = try readBytes(from: data, at: &offset)
            
            // Use raw components to create RSA key
            let rsaKey = try _RSA.Signing.PrivateKey(
                n: stripMPIntPadding(n),
                e: stripMPIntPadding(e),
                d: stripMPIntPadding(d),
                p: stripMPIntPadding(p),
                q: stripMPIntPadding(q)
            )
            logger.info("🔑 Parsed RSA key")
            return NIOSSHPrivateKey(rsaKey: rsaKey)
            
        default:
            throw SSHKeyParseError.unsupportedFormat("Key type \(keyType)")
        }
    }
}
